version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: barber-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: barber
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: >
      postgres
      -c listen_addresses='*'
      -c password_encryption=scram-sha-256

volumes:
  pgdata:
